/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 28-may.-2019 20:06:01 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `Cliente` CASCADE
;

DROP TABLE IF EXISTS `ClienteMesa` CASCADE
;

DROP TABLE IF EXISTS `Consumo` CASCADE
;

DROP TABLE IF EXISTS `Menu` CASCADE
;

DROP TABLE IF EXISTS `Mesa` CASCADE
;

DROP TABLE IF EXISTS `Mesero` CASCADE
;

DROP TABLE IF EXISTS `MeseroMesa` CASCADE
;

DROP TABLE IF EXISTS `Venta` CASCADE
;

/* Create Tables */

CREATE TABLE `Cliente`
(
	`IDCliente` INT NOT NULL,
	`Nombre` VARCHAR(30) NOT NULL,
	`ApPat` VARCHAR(60) NOT NULL,
	`ApMat` VARCHAR(60) NOT NULL,
	`Nac` DATE NOT NULL,
	`RFC` VARCHAR(13) NULL,
	`Tel` VARCHAR(12) NULL,
	`Dir` VARCHAR(200) NULL,
	CONSTRAINT `PK_Cliente` PRIMARY KEY (`IDCliente` ASC)
)

;

CREATE TABLE `ClienteMesa`
(
	`IDMesa1` INT NOT NULL,
	`IDMesa2` INT NULL DEFAULT NULL,
	`IDCliente` INT NOT NULL
)

;

CREATE TABLE `Consumo`
(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`IDVenta` INT NOT NULL,
	`IDPlatillo` INT NOT NULL,
	`Cantidad` INT NOT NULL,
	`Total` DOUBLE(10,0) NOT NULL,
	CONSTRAINT `PK_Consumo` PRIMARY KEY (`ID` ASC)
)

;

CREATE TABLE `Menu`
(
	`IDPlatillo` INT NOT NULL,
	`Desc` VARCHAR(200) NOT NULL,
	`Tipo` CHAR(2) NOT NULL,
	`Precio` DOUBLE(10,2) NOT NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`IDPlatillo` ASC)
)

;

CREATE TABLE `Mesa`
(
	`IDMesa` INT NOT NULL,
	`Cantidad` INT NULL,
	CONSTRAINT `PK_Mesa` PRIMARY KEY (`IDMesa` ASC)
)

;

CREATE TABLE `Mesero`
(
	`IDEmp` INT NOT NULL,
	`Nombre` VARCHAR(30) NOT NULL,
	`ApPat` VARCHAR(60) NOT NULL,
	`ApMat` VARCHAR(60) NOT NULL,
	`Tel` VARCHAR(12) NOT NULL,
	`Correo` VARCHAR(40) NOT NULL,
	`Dir` VARCHAR(200) NOT NULL,
	`Sueldo` DOUBLE(10,2) NOT NULL,
	`Horario` VARCHAR(15) NOT NULL,
	CONSTRAINT `PK_Mesero` PRIMARY KEY (`IDEmp` ASC)
)

;

CREATE TABLE `MeseroMesa`
(
	`IDMesero` INT NOT NULL,
	`IDMesa` INT NOT NULL
)

;

CREATE TABLE `Venta`
(
	`IDVenta` INT NOT NULL,
	`IDCliente` INT NOT NULL,
	`CantidadTotal` INT NOT NULL,
	`SubTotal` DOUBLE(10,2) NOT NULL,
	`IVA` DOUBLE(10,2) NOT NULL,
	`Total` DOUBLE(10,2) NOT NULL,
	`Fecha` DATE NOT NULL,
	`Hora` TIME NOT NULL,
	CONSTRAINT `PK_Venta` PRIMARY KEY (`IDVenta` ASC)
)

;

/* Create Foreign Key Constraints */

ALTER TABLE `ClienteMesa` 
 ADD CONSTRAINT `FK_ClienteMesa_Cliente`
	FOREIGN KEY (`IDCliente`) REFERENCES `Cliente` (`IDCliente`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `ClienteMesa` 
 ADD CONSTRAINT `FK_ClienteMesa_Mesa`
	FOREIGN KEY (`IDMesa1`) REFERENCES `Mesa` (`IDMesa`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `ClienteMesa` 
 ADD CONSTRAINT `FK_ClienteMesa_Mesa_02`
	FOREIGN KEY (`IDMesa2`) REFERENCES `Mesa` (`IDMesa`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Consumo` 
 ADD CONSTRAINT `FK_Consumo_Menu`
	FOREIGN KEY (`IDPlatillo`) REFERENCES `Menu` (`IDPlatillo`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Consumo` 
 ADD CONSTRAINT `FK_Consumo_Venta`
	FOREIGN KEY (`IDVenta`) REFERENCES `Venta` (`IDVenta`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `MeseroMesa` 
 ADD CONSTRAINT `FK_MeseroMesa_Mesa`
	FOREIGN KEY (`IDMesa`) REFERENCES `Mesa` (`IDMesa`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `MeseroMesa` 
 ADD CONSTRAINT `FK_MeseroMesa_Mesero`
	FOREIGN KEY (`IDMesero`) REFERENCES `Mesero` (`IDEmp`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Venta` 
 ADD CONSTRAINT `FK_Venta_Cliente`
	FOREIGN KEY (`IDCliente`) REFERENCES `Cliente` (`IDCliente`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1 
;
